version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prisma-task-management-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prisma-task-management-api
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}